export const A_SUBIDA_ASSETS = {
  depoisDaVirada: {
    src: "/images/story/cave-first-turn-cliffhanger-v1.png",
    width: 1672,
    height: 941,
    alt: "Na lição passada: o prisioneiro olha para trás e vê, atrás da parede, uma pessoa carregando dois objetos que na sombra se misturam",
    focalPoint: { x: 0.45, y: 0.62 },
  },
  fogoEEstatuas: {
    src: "/images/story/a-subida/beat-02-fogo-e-estatuas-v1.png",
    width: 1672,
    height: 941,
    alt: "O prisioneiro em pé atrás da parede baixa vê o fogo alto, as figuras que carregam objetos e as sombras que esses objetos projetam",
    focalPoint: { x: 0.58, y: 0.55 },
  },
  feixeDeLuz: {
    src: "/images/story/a-subida/beat-03b-feixe-de-luz-v1.png",
    width: 1672,
    height: 941,
    alt: "Ainda dentro da caverna, o prisioneiro olha para um feixe de luz que vem de uma passagem à frente",
    focalPoint: { x: 0.62, y: 0.48 },
  },
  aSubidaDolorosa: {
    src: "/images/story/a-subida/beat-03-a-subida-dolorosa-v1.png",
    width: 1672,
    height: 941,
    alt: "O mesmo prisioneiro da lição passada sobe a passagem íngreme da caverna em direção à entrada, sem cobrir os olhos",
    focalPoint: { x: 0.58, y: 0.48 },
  },
  platoOfuscado: {
    src: "/images/story/a-subida/beat-04-plato-ofuscado-v1.png",
    width: 1024,
    height: 1024,
    alt: "Platão estende as mãos abertas na direção de um cartão de conceito, apresentando a palavra periagōgē",
    focalPoint: { x: 0.5, y: 0.42 },
  },
  sombrasLaFora: {
    src: "/images/story/a-subida/beat-05-sombras-la-fora-v1.png",
    width: 1672,
    height: 941,
    alt: "Do lado de fora da caverna, o prisioneiro senta-se em uma pedra baixa e olha hesitante para a sombra projetada no chão sob a luz do crepúsculo",
    focalPoint: { x: 0.4, y: 0.55 },
  },
  reflexosNaAgua: {
    src: "/images/story/a-subida/beat-06-reflexos-na-agua-v1.png",
    width: 1672,
    height: 941,
    alt: "O prisioneiro se ajoelha à beira da água e aponta do reflexo de uma árvore e de uma pedra para os objetos reais acima da margem",
    focalPoint: { x: 0.42, y: 0.58 },
  },
  objetosEstrelasELua: {
    src: "/images/story/a-subida/beat-07-arvore-de-dia-v2.png",
    width: 1672,
    height: 941,
    alt: "Fora da caverna, de dia, o sol bate na árvore e o prisioneiro olha a sombra nítida no chão",
    focalPoint: { x: 0.55, y: 0.55 },
  },
  oSol: {
    src: "/images/story/a-subida/beat-08-o-sol-v1.png",
    width: 1672,
    height: 941,
    alt: "O prisioneiro sai da boca da caverna para a paisagem aberta e cobre os olhos com a mão porque o sol está forte demais",
    focalPoint: { x: 0.4, y: 0.45 },
  },
  olharACaverna: {
    src: "/images/story/a-subida/beat-10-olhar-a-caverna-v1.png",
    width: 1672,
    height: 941,
    alt: "Fora da caverna, o prisioneiro olha pensativo para a entrada, receoso de voltar e ser julgado",
    focalPoint: { x: 0.42, y: 0.48 },
  },
  recorteAgora: {
    src: "/images/story/a-subida/beat-09-video-cortado-v3.png",
    width: 1672,
    height: 941,
    alt: "Um adolescente no pátio da escola olha o celular; vemos a traseira do aparelho, com as câmeras",
    focalPoint: { x: 0.52, y: 0.48 },
  },
} as const;

export type ASubidaAssetKey = keyof typeof A_SUBIDA_ASSETS;
